version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
